#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"show_img": "00_trajectory.ipynb",
         "sliceImage": "00_trajectory.ipynb",
         "rotate": "00_trajectory.ipynb",
         "get_image_patch": "00_trajectory.ipynb",
         "Trajectory": "00_trajectory.ipynb",
         "mark_key_points": "00_trajectory.ipynb",
         "fib": "05_test.ipynb"}

modules = ["trajectory.py",
           "test.py",
           "index.py"]

git_url = "https://github.com/johnnewto/boxsim/boxsim/tree/master/"

def custom_doc_links(name): return None